name: Repository Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grant permission
        run: chmod +x build.sh

      - name: Run structure check
        run: ./build.sh
